#!/bin/bash
HERE="$(dirname "$(readlink -f "$0")")"
export APPDIR="$HERE/usr/bin"

# Add the lib directory to LD_LIBRARY_PATH
export LD_LIBRARY_PATH="$HERE/usr/lib:$LD_LIBRARY_PATH"

# Execute the application
exec "$Here/usr/bin/a.out" "$@"

